name: Check @learn-react/catalog

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "apps/catalog/**"

jobs:
  check_catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Initialize
        uses: ./.github/actions/restore-node

      - name: Build builder & icon
        run: pnpm builder build && pnpm icon build

      - name: Build
        run: pnpm catalog build

      - name: Lint
        run: pnpm catalog lint

      - name: Test
        run: pnpm catalog test
